# Generated by Django 3.2.8 on 2022-10-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mahasiswa_id', models.CharField(max_length=10)),
                ('Nama', models.CharField(max_length=100)),
                ('Fakultas', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Mahasiswa',
            },
        ),
    ]
